# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LinguÁgil 2018
skills: "O maior evento sobre linguagens de programação e metodologias ágeis de Salvador"
#skills: "Em 2018, o LinguÁgil chega à sua 8º edição! No total, já tivemos 1600 participantes de Salvador e do Brasil, 89 palestras, 21 workshops: muitas horas de conhecimento e muita mão na massa."
email: linguagil@linguagil.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
keywords: "your keywords, separated by commas"
twitter_username: linguagil
github_username:  linguagil
meta_author: LinguÁgil
registration_link: https://inscricoes.agilebrazil.com/login

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: linguagil

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c
  primary-rgb: "24,288,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: Grupo LinguÁgil
  location: Salvador
  social: linguagil
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/linguagil
  - title: facebook
    url: https://www.facebook.com/linguagil
  - title: github
    url: https://github.com/linguagil
  - title: instagram
    url: https://www.instagram.com/linguagil/

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Tema baseado no projeto <a href="/">Start Bootstrap</a>, sob as licença <a href="https://opensource.org/licenses/MIT">MIT</a>;
                       is a project created and maintained by
                       <a href="http://davidmiller.io">David Miller</a>
                       at
                       <a href="http://blackrockdigital.io">Blackrock Digital</a>.
                       <br>
                       Themes and templates licensed
                       <a href="https://opensource.org/licenses/MIT">MIT</a>, Start Bootstrap website
                       <a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.
                       <br>
                       Based on
                       <a href="http://getbootstrap.com">Bootstrap</a>.
                       </div>
Baseado no tema Freelancer,  is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
# plugins:
#   - jekyll-feed